Update README.dev.md
tortellini-tools/action pull request #129
Opened 2021-06-08 14:26 UTC by jspaaks

## Description

Updated dev notes to take into account the values of `INPUT_CURATIONS`, `INPUT_CLASSIFICATIONS` and `INPUT_RULES`.

Refs: #123

* * *

## Before you get started

- [ ] I read and I followed [contributing guidelines](https://github.com/tortellini-tools/action/blob/main/CONTRIBUTING.md)
- [ ] [☝ Create an issue](https://github.com/NLeSC/licenseguard/issues/new/choose) to discuss what you are going to do

## Checklist

This section should be filled in by the creator of this pull request to make sure the pull request is ready to review.

- [ ] This pull request has a descriptive title
- [ ] Code is written according to the code quality guidelines
- [ ] Documentation if applicable is available
- [ ] Tests run successfully
- [ ] All checks below this pull request were successful

## Instructions to review the pull request

2021-06-09 12:22 UTC, eriktks requested changes
Tested instructions in [README.dev.md section Run the analysis](https://github.com/tortellini-tools/action/blob/main/README.dev.md#run-the-analysis) before and after PR. Both instruction sets failed as reported in the issue. The problems with the [second instruction set](https://github.com/tortellini-tools/action/blob/main/README.dev.md#on-other-repositories) were solved by this PR but not the ones of the [first instruction set](https://github.com/tortellini-tools/action/blob/main/README.dev.md#on-the-current-repository). But these can be solved as well by copying three lines of the present solution over there.

2021-06-09 12:22 UTC, eriktks commented on README.dev.md
> +export INPUT_CLASSIFICATIONS=https://github.com/NLeSC/tortellini-on-rsd/raw/main/config/license-classifications.yml
The reported error in the issue also occurs when running on the current repository. It will help if these three lines (110-112) are also inserted before line 94.

2021-06-10 16:51 UTC, jspaaks commented on README.dev.md
> +export INPUT_CLASSIFICATIONS=https://github.com/NLeSC/tortellini-on-rsd/raw/main/config/license-classifications.yml
done in https://github.com/tortellini-tools/action/pull/129/commits/4d4707620cd48b753a2a9039fef3b3574172ea9d (slightly differntly than what you suggested)

2021-06-11 07:37 UTC, sverhoeven approved these changes
The commands work as expected, with output in documented places.

2021-06-14 08:20 UTC, eriktks approved these changes
Great, thanks!

2021-06-14 08:37 UTC, jspaaks commented
Thanks reviewers

2021-06-14 08:37 UTC, merged